### ISSUE TITLE
AssertionError: Non-existent Key: train.dataset

### ISSUE THREAD

**Issue by jinglan0829** [zju3dv/clean-pvnet#2]
感谢作者提供的干净版本的pvnet! 当我运行了python run.py --type visualize --cfg_file configs/linemod.yaml train.datset CustomTrain test.dataset CustomTrain model mycat这个以后，出现了这种error, AssertionError: Non-existent Key: train.dataset，该如何解决呢？

**Comment by pengsida** [comment]
你字打错了 `train.datset` -> `train.dataset`

**Comment by jinglan0829** [comment]
我直接复制粘贴了，不好意思呀，没仔细看

**Comment by jinglan0829** [comment]
![image](https://user-images.githubusercontent.com/58730170/70969939-78393680-20e0-11ea-8b94-5b2bd6064547.png) 出来的结果不太对呀，自己数据集的train.json文件该如何获取呢？

**Comment by pengsida** [comment]
第一个问题：https://github.com/zju3dv/clean-pvnet/issues/1
第二个问题：https://github.com/zju3dv/clean-pvnet#training-on-the-custom-object

**Comment by ykim104** [comment]
I get this error when using custom dataset :(
`
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:103: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [0,0,0], thread: [677,0,0] Assertion `t >= 0 && t < n_classes` failed.
`
This happens when I call the dataloader - it might be that the computer annotations are wrong?
It doesn't happen all the time for every image, but often enough. 
I could't locate where you compute vector field annotation - could you give me a hint?

Thank you in advance and thank you for publishing this repo!

**Comment by pengsida** [comment]
I will check this problem.

**Comment by ykim104** [comment]
so actually I think this happens inside  `output, loss, loss_stats, image_stats = self.network(batch)`

**Comment by pengsida** [comment]
Vector field: https://github.com/zju3dv/clean-pvnet/blob/master/lib/datasets/linemod/pvnet.py#L53
This problem is probably caused by segmentation not vector field.

**Comment by ykim104** [comment]
yes i found out that I get error here `seg_loss = self.seg_crit(output['seg'], mask)`

Do you have a recommendation to fix this ?

**Comment by ykim104** [comment]
ohhh I printed my mask values and I have a 0's and 255 intead of 1 for mask... This could be the cause this problem?

**Comment by pengsida** [comment]
The mask contains other values?

**Comment by ykim104** [comment]
Yess!! I had 255 instead 1's in my mask!
I also used ObjectDatasetTool but my masks were 2D 
so I edited pvnet_data_utils.py :D 

`    if ann_type == 'real':
        try:
	        return (np.asarray(Image.open(path))[:, :, 0] != 0).astype(np.uint8) # custom/custom mask return 3d matrix
        except:
	        return (np.asarray(Image.open(path))).astype(np.uint8)/255.`

**Comment by ykim104** [comment]
It works now!!! Thank you!

By the way, I also made few edits so I can have multiple object dataset inside custom folder. :D

**Comment by pengsida** [comment]
`(np.asarray(Image.open(path)) != 0).astype(np.uint8)` is a more safe way, since the background value is zero in most cases.
You could additionally define a custom dataloader for your dataset according to https://github.com/zju3dv/clean-pvnet/blob/master/project_structure.md
I feel happy if this project facilitate your work!
