### ISSUE TITLE
Training TIme

### ISSUE THREAD

**Issue by kevin860213** [zju3dv/clean-pvnet#4]
Can i ask how many gpus and what kind do you use in this new project?
And, how much time did it cost?
Thanks

**Comment by pengsida** [comment]
gpus: https://github.com/zju3dv/clean-pvnet/blob/master/configs/linemod.yaml#L7
time: 12h33m

**Comment by kevin860213** [comment]
Thanks, did you try to train on single gpu?

**Comment by pengsida** [comment]
No, you could try it and watch the output curve.

**Comment by mentian** [comment]
> gpus: https://github.com/zju3dv/clean-pvnet/blob/master/configs/linemod.yaml#L7
> time: 12h33m

Hi, Sida,
I trained with your original code on "cat" model, except that I use two gpus (Titan X and 1080Ti). It takes about 50 mins for one epoch (about 20000 images, batch size=16). Would you have any suggestion about this? I assume it only takes around less than 4 mins for one epoch (240 epochs takes 12h33m) during your training.

**Comment by pengsida** [comment]
What is your pytorch version?

**Comment by mentian** [comment]
Pytorch 1.1.0 with CUDA 9.0, as indicated in your README. As far as I know, all the differences from your setting are the system version (Ubuntu 18.04), and I use 2 GPUS (one Titan X and one 1080 Ti), batch size is reduced to 16 accordingly. Then it takes around 50 mins for one epoch, which is far from twice of your time. Since I exactly follow your installation guide, except the differences I mentioned, I would really appreciate if you could suggest what might be the reason for this.

**Comment by pengsida** [comment]
I found that dilated convolution is very slow in pytorch 1.1 with cuda 9.0.
You could try pytorch 0.4.1, which I used to train the network.

**Comment by mentian** [comment]
Thanks a lot, I would try that and let you know if I can reproduce your training time.

**Comment by mentian** [comment]
With pytorch 0.4.1, one epoch takes about 10 mins (2 GPUs). Thanks for you help.
