### ISSUE TITLE
Thoughts on my inference output for a custom dataset.

### ISSUE THREAD

**Issue by ishangupta3** [zju3dv/clean-pvnet#48]
I have run an inference on an object of 'scissors' - a custom dataset. The output seems to be all over the place. While some are great to detect the pose, some are not. Do you have any thoughts?

![plot21](https://user-images.githubusercontent.com/8518915/77088862-4d51cd80-69c2-11ea-946b-a4dfe9f011fc.png)
![plot185](https://user-images.githubusercontent.com/8518915/77088889-55117200-69c2-11ea-8f73-239e351fc0de.png)
![plot15](https://user-images.githubusercontent.com/8518915/77088912-5c388000-69c2-11ea-81f9-1248469d3619.png)
![plot72](https://user-images.githubusercontent.com/8518915/77088925-5fcc0700-69c2-11ea-99e7-1b8750bb6a2b.png)
![plot4](https://user-images.githubusercontent.com/8518915/77088959-6a869c00-69c2-11ea-8a5e-746e63960f78.png)

**Comment by pengsida** [comment]
I think that the performance is quite natural.
You could adjust the training strategy to improve the performance.

**Comment by ishangupta3** [comment]
What ways do you recommend to adjust the training strategy?

**Comment by pengsida** [comment]
Proper data augmentation.

**Comment by shanniruo** [comment]
@ishangupta3 hi ,have you solved the problem? now i also test  on a custom dataset. but the result is bad, I'm not even sure if there's something wrong with some of my actions .you should use the ObjectDatasetTools, i use the timer video provided by author .If the pose is same as transforms in ObjectDatasetTools? and the model.py is same as registeredScene.py? i modified the name and the transforms folder so that it can be trained.can you give me some guidance

**Comment by KAOeric** [comment]
Sorry, I would like to ask how did you train your custom data when run with the command `python run.py --type custom`, I got some error
